name: 'Setup nodejs'
description: Setup nodejs
runs:
  using: "composite"
  steps:
    - name: Read .node-version
      shell: bash
      id: read-node-version
      run: echo "version=$(cat .node-version)" >> "$GITHUB_OUTPUT"

    - name: Install wasm-pack
      shell: bash
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.read-node-version.outputs.version }}
