name: 'Setup nodejs'
description: Setup nodejs and other frontend tools used in the frontend build
runs:
  using: "composite"
  steps:
    - name: Read .node-version
      shell: bash
      id: read-node-version
      run: echo "version=$(cat .node-version)" >> "$GITHUB_OUTPUT"

    - name: Install wasm-pack
      shell: bash
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        cargo --version
        wasm-pack --version

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.read-node-version.outputs.version }}
