name: 'release notes'
description: 'Prepares release notes, including download links for our artifacts.'
inputs:
    assets:
        description: "Assets to upload"
        required: true
        default: ""
    production_asset:
        description: "Name of the production asset"
        required: true
        default: ""
    changelog:
        description: "Content of the changelog section"
        required: true
        default: ""
    workflow_jobs:
      description: "JSON array of workflow jobs (to generate the links to the workflow runs)"
      required: true
      default: ""
outputs:
  notes-file:
    description: The release-notes file
    value: ${{ steps.release-notes.outputs.notes-file }}
runs:
    using: 'composite'
    steps:
      - name: 'Create release notes'
        shell: bash
        id: release-notes
        env:
          INPUT_PRODUCTION_ASSET: ${{ inputs.production_asset }}
          INPUT_ASSETS: ${{ inputs.assets }}
          INPUT_CHANGELOG: ${{ inputs.changelog }}
          INPUT_WORKFLOW_JOBS: ${{ inputs.workflow_jobs }}
        run: |
          ${{ github.action_path }}/run.sh
