name: 'release notes'
description: 'Prepares release notes, including download links for our artifacts.'
inputs:
    assets:
        description: "Assets to upload"
        required: true
        default: ""
    production_asset:
        description: "Name of the production asset"
        required: true
        default: ""
    token:
        description: "GitHub authentication token"
        required: true
        default: ""
outputs:
  notes-file:
    description: The release-notes file
    value: ${{ steps.release-notes.outputs.notes-file }}
runs:
    using: 'composite'
    steps:
      - name: 'Create release notes'
        shell: bash
        id: release-notes
        env:
          INPUT_PRODUCTION_ASSET: ${{ inputs.production_asset }}
          INPUT_ASSETS: ${{ inputs.assets }}
          INPUT_TOKEN: ${{ inputs.token }}
        run: |
          ${{ github.action_path }}/run.sh
          
