= How to use the Internet Identity service
:keywords: Internet Computer,blockchain,protocol,replica,subnet,data center,canister,developer
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK

The Internet Identity service enables you to authenticate securely and anonymously when you access applications that use the service as an authentication method. A different identity is created for each application you log in to, and you will be able to use all of your registered devices or authentication methods to log in to the same account. 

Unlike most authentication services, your Internet identity does not require you to set and manage passwords, generate a cryptographically-secure seed phrase, or provide any personal identifying information to applications or to the service. Instead, you create authentication profiles that use the authentication methods you choose such as facial recognition from a smartphone, your computer unlock password, or a security key. 

== Create an Internet identity

You can access applications running in the {IC} securely by selecting an authentication method and having an Internet Identity user number generated for you.

When you first access an application running on the {IC}, you are directed to the Internet Identity service and asked to enter a User Number to log in. If you are a new user, you need to register first.

To create an Internet Identity as a first-time user:

. Click *Register with Internet Identity*. 

. Enter a name for the device profile you’re using to create your Internet identity. For example: iPhone, or YubiKey. 

. Choose to authenticate using either a security key, or with an authentication method of the device you are using, if that option is available. 
+
For example, if your device has biometrics enabled, you might see the option to use those as your authentication method. You can also use the password that unlocks your computer or a pin that unlocks your phone, depending on the device you’re using.
+

NOTE: As a best practice, use a dedicated security key. You can then add another authentication device if you prefer to use one, such as your phone, and store the key in a safe place in the event that you are unable to to use your preferred device.  

. Click *Register* when prompted. 
+
Your identity is not created until you perform this step. 
. Save your *User Number*.
+
When you have registered your device, you’ll receive a *User Number*. 
+
This number is unique, but it is not a secret, so you should save the number in multiple places. 
Your browser will remember your user number, but you will need it if you log in on a different computer, or if you clear your browser state. 
If you lose your User Number and are logged out on all devices, you cannot log in to the Identity service to manage your devices, or access any of your applications.
. Click Continue. 
+
On the next screen, you will see your User Number and your registered authentication devices. 
From there, you can only remove devices. To add another method of authentication, you must  access the Internet Identity service from the device you want to add. 

== Add a device 

The workflow for adding a device can vary depending on what device profiles you’ve already added to your identity. For example, if you first authorized your computer to create your User Number, and you’d like to add your phone as a second authentication method, you must be able to authenticate your phone on the authorized computer. You must always be able to authorize the device you’re adding, using a device that is already authorized.
 
EXAMPLE: Register your phone as an additional authentication method
Note that you can also set up your initial Internet identity on your phone.

. Open the Internet Identity service in your phone’s browser. 

. Click *Already registered but using a new device?*

. Enter your User Number and click *Continue*.

. Click *GET STARTED*. 

. Select *Use this device with screen lock*. 
+
You will be asked to unlock the device. 
+

NOTE: To use the screen lock option, you have to have screen lock activated on your phone. To unlock your phone, either use biometric authentication or a pin number. 

. Authorize your phone.
+
After you’ve unlocked your phone, you will be provided with a URL and a QR code. You must use the URL or QR code in a browser in the computer that has already been authorized. For example, you can copy the URL and email it to yourself, then paste it into a browser on the computer. 
. Enter your User Number and click *Login*.
. Link your phone to your identity. 
+
If you’re sure that the link you pasted in the browser came from you, click Yes, link new device.
. Give the device profile a name and click Link Device.
+
Your phone will be redirected to the login page, and you can now use it to log in.
