= What is Internet Identity?
:keywords: Internet Computer,blockchain,protocol,replica,subnet,data center,canister,developer
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK

Internet Identity enables you to authenticate securely and anonymously when you access applications that use it as an authentication method. A different identity that is not connected to you in any way is created for each application you log in to, and you will be able to use all of your registered devices or authentication methods to log in to the different applications. 

Unlike most authentication services, your Internet Identities do not require you to set and manage passwords or provide any personal identifying information to applications. Instead, you use the authentication profiles that your devices use such as facial recognition from a smartphone, your computer unlock password, or a security key.

[[id-overview]]
== How Internet Identity works

Internet Identity takes advantage of the Web Authentication (WebAuthn) API to provide secure cryptographic authentication for applications running on the {IC}.This enables you to use security chips built into your smart phone or your laptop or security keys that can be recognized by your computer and phone to authenticate you and to authorize access to an application. 

Applications that integrate with Internet Identity prompt you to register or log in with a previously-registered ID number. 
Registering a device is a simple process that generates a unique, public cryptographic key for you that is stored on the Internet Computer blockchain and represented by an ID number. You can then use your ID number and original authorized device to register additional devices, so that you can access applications across all of your devices. These public keys are paired with a private keys that are generated by each device's security chip, and these private keys never leave your device. 

When you access an application that uses the Internet Identity authentication method, you are redirected to Internet Identity. Internet Identity receives a signature generated by the private key when you authenticate. Internet Identity recognizes the signature and pairs it with your ID number. Your browser is then authorized to redirect you, logged in with an anymous identity, to the {IC} application. 
 
While different identities are created for each application you access, you only need your ID number and any of your registered devices to access every app. Your devices just represent different methods you can use to authenticate your ID number. 

Additionally, you can register as many identities with different ID numbers as you want for redundancy, to set up different device authentication profiles for other device users, or to ensure access to services that use the Internet Identity. However, it is important to note that if you lose your ID number, you will not be able to login to any app with the original identity created for you that is associated with the number. Even if you create a different ID number, with all of the same authentication devices as the original, the key pair will be different, and a new identity will be created for each app. Don't lose your ID number!

== Identity recovery
When you register an identity, you will be prompted to copy a cryptographically-secure seed phrase (this includes your identification number as the first entry) or to add a dedicated security key for recovery purposes. 

You can choose to do this at any time, but note that if you lose your ID number or if you no longer have access to authorized devices, you will need the seed-phrase or the recovery security key to recover your identity. Without one of these, you will be locked out of any applications that require the associated identity. 

To learn how to register a device step-by-step, see: link:https://sdk.dfinity.org/docs/ic-identity-guide/auth-how-to.html[How to use Internet Identity]. 



////

== Want to learn more?

If you are looking for more information about authentication options and using Internet identity, check out the following related resources:

* link:https://www.youtube.com/watch?v=XgsOKP224Zw[Overview of the Internet Computer (video)]
* link:https://www.youtube.com/watch?v=jduSMHxdYD8[Building on the {IC}: Fundamentals (video)]
* link:https://www.youtube.com/watch?v=LKpGuBOXxtQ[Introducing Canisters — An Evolution of Smart Contracts (video)]
* link:https://dfinity.org/faq/[Frequently Asked Questions (video and short articles)]

////
