= What is Internet Identity?
:keywords: Internet Computer,blockchain,protocol,replica,subnet,data center,canister,developer
:proglang: Motoko
:platform: Internet Computer platform
:IC: Internet Computer
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK

Internet Identity enables you to authenticate securely and anonymously when you access applications that use it as an authentication method. A different identity is created for each application you log in to, and you will be able to use all of your registered devices or authentication methods to log in to the same account. 

Unlike most authentication services, your Internet Identities do not require you to set and manage passwords or provide any personal identifying information to applications. Instead, you use the authentication profiles that you create such as facial recognition from a smartphone, your computer unlock password, or a security key.

[[id-overview]]
== How Internet Identity works

Internet Identity takes advantage of the Web Authentication (WebAuthn) API to provide secure cryptographic authentication using smart contracts for applications running on the {IC}. 
Internet Identity enables you to use security modules built into your smart phone, your laptop or security keys plugged into the USB port of your computer to verify your identity and authorize access to an application.

Applications that integrate with Internet Identity prompt you to authenticate with an Identity Anchor. If you don't have an Identity Anchor yet, creating one is a simple process that generates a unique cryptographic key for you that is stored on the Internet Computer blockchain. You can then use your Identity Anchor to add additional devices, so that you can access applications across all of your devices.

When you access an application that uses Internet Identity for authentication, you first specify the Identity Anchor you want to use. After authenticating using an authentication method for this Identity Anchor, your browser connects to Internet Identity and generates a key for use with that application.
Finally, you are asked to authorize access to the application.

Your browser downloads the authorization, then redirects you to the application.
The application verifies the authorization from Internet Identity and grants you access as an application-specific anonymous identity that we call pseudonym.
Internally, you have a different pseudonym for each application, but your pseudonym for any single application is the same across all of your devices.
All of your devices just represent different methods you can use to authenticate your Identity Anchor. 

You can register as many Identity Anchors as you want for redundancy, to set up different device authentication profiles for other device users, or to ensure access to services that use Internet Identity.

== How to use Internet Identity
To learn how create and use Identity Anchors step-by-step, see: link:https://sdk.dfinity.org/docs/ic-identity-guide/auth-how-to.html[How to use Internet Identity]. This also describes how to set up recovery mechanisms for Identity Anchors.

////

== Want to learn more?

If you are looking for more information about authentication options and using Internet identity, check out the following related resources:

* link:https://www.youtube.com/watch?v=XgsOKP224Zw[Overview of the Internet Computer (video)]
* link:https://www.youtube.com/watch?v=jduSMHxdYD8[Building on the {IC}: Fundamentals (video)]
* link:https://www.youtube.com/watch?v=LKpGuBOXxtQ[Introducing Canisters — An Evolution of Smart Contracts (video)]
* link:https://dfinity.org/faq/[Frequently Asked Questions (video and short articles)]

////
