name: Install Rust
description: Installs rust
inputs:
  rustc_version:
    description: 'Rust toolchain version'
    required: true
runs:
  using: composite
  steps:
      - name: Install Rust
        shell: bash
        run: |
          rustup update "$RUSTC_VERSION" --no-self-update
          rustup default "$RUSTC_VERSION"
          rustup target add wasm32-unknown-unknown
          rustup component add rustfmt
