#!/usr/bin/env bash

set -euo pipefail

function build_canister() {
    local canister=$1

    echo "Building $canister"

    SRC_DIR="$PWD/../$canister"
    TARGET="wasm32-unknown-unknown"
    # standardize source references
    CARGO_HOME="${CARGO_HOME:-"$HOME/.cargo"}"
    RUSTFLAGS="--remap-path-prefix $CARGO_HOME=/cargo"

    cargo_build_args=(
        --manifest-path "$SRC_DIR/Cargo.toml"
        --target "$TARGET"
        --release
        )

    echo Running cargo build "${cargo_build_args[@]}"
    echo RUSTFLAGS: "$RUSTFLAGS"

    RUSTFLAGS="$RUSTFLAGS" cargo build "${cargo_build_args[@]}"

    CARGO_TARGET_DIR="$SRC_DIR/target"

    ic-wasm \
          "$CARGO_TARGET_DIR/$TARGET/release/$canister.wasm" \
          -o "./$canister.wasm" \
          shrink
    # wasm-snip $canister.wasm -o $canister.wasm __wbindgen_object_drop_ref __wbindgen_placeholder
    ic-wasm "$canister.wasm" -o "$canister.wasm" metadata candid:service -f "$SRC_DIR/$canister.did" -v public
    # gzip --no-name --force "$canister.wasm"
    # mv $canister.wasm.gz $SRC_DIR
}

build_canister $1
