[package]
name = "vc_util_js"
version = "1.0.0"
edition = "2021"
license-file = "LICENSE"

# TODO: fill the rest:

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
candid.workspace = true
vc_util.workspace = true
wasm-bindgen = "0.2"
