#!/usr/bin/env bash

set -euo pipefail

JAILBREAK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$JAILBREAK_DIR"

git format-patch --stdout main..HEAD -- ':!jailbreak/' > jailbreak.patch
