name: 'Setup didc'
description: Setup didc
runs:
  using: "composite"
  steps:
    - name: Install didc
      shell: bash
      run: |
        didc_release=$(sed <.didc-release 's/#.*$//' | sed '/^$/d')

        # Actual install
        mkdir -p ~/.local/bin
        curl --location --silent --show-error \
          https://github.com/dfinity/candid/releases/download/$didc_release/didc-linux64 \
          -o ~/.local/bin/didc
        chmod +x ~/.local/bin/didc
        ~/.local/bin/didc --version
        echo "$HOME/.local/bin" >> $GITHUB_PATH
