[package]
name = "certified_map"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashtree = { path = "../hashtree" }

[dev-dependencies]
hex = "0.4"
