#!/usr/bin/env bash
# install build dependencies (rustup + ic-wasm)

set -euo pipefail

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPTS_DIR/.."

function run() {
    1>&2 echo "running $@"
    rc=0 && "$@" || rc="$?"
    if ! [ "$rc" -eq 0 ]
    then
        1>&2 echo "Bootstrap command failed: $@"
        exit "$rc"
    fi
}

rust_version=$(cat ./rust-toolchain.toml | sed -n 's/^channel[[:space:]]*=[[:space:]]"\(.*\)"/\1/p')
echo "using rust version '$rust_version'"

# here we set the toolchain to 'none' and rustup will pick up on ./rust-toolchain.toml
run curl --fail https://raw.githubusercontent.com/rust-lang/rustup/refs/tags/1.28.1/rustup-init.sh -sSf | run sh -s -- -y --default-toolchain "none" --no-modify-path

# https://blog.rust-lang.org/2025/03/04/Rustup-1.28.1.html
# Install required toolchain
run rustup toolchain install "$rust_version"
# Set the default toolchain to the required version
run rustup default "$rust_version"

targets=$(sed -n 's/^targets[[:space:]]*=[[:space:]]\[\(.*\)\]/\1/p' ./rust-toolchain.toml | tr -d '[]" ' | tr ',' ' ')
echo "using rust targets: $targets"

echo "Rust toolchain version $(rustc --version) installed."

# Install Rust targets
for target in $targets; do
    run rustup target add "$target"
done

echo "looking for ic-wasm 0.8.5"
if [[ ! "$(command -v ic-wasm)" || "$(ic-wasm --version)" != "ic-wasm 0.8.5" ]]
then
    echo "installing ic-wasm 0.8.5"
    run cargo install ic-wasm --version 0.8.5 --force
fi

# make sure the packages are actually installed (rustup waits for the first invoke to lazyload)
cargo --version
cargo clippy --version
cargo fmt --version
