#!/usr/bin/env bash
# vim: ft=bash
# Build internet_identity.wasm inside docker. This outputs a single file, internet_identity.wasm,
# in the top-level directory.

set -euo pipefail

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$SCRIPTS_DIR/.."

echo "PWD: $PWD"

image_name="internet-identity"
docker_build_args=( --target scratch )

II_ENV=${II_ENV:-}
echo "II_ENV: '$II_ENV'"

if [ -n "$II_ENV" ]
then
    docker_build_args+=( --build-arg II_ENV="$II_ENV" )
    image_name="$image_name-$II_ENV"
fi

USE_DUMMY_CAPTCHA=${USE_DUMMY_CAPTCHA:-}
echo "USE_DUMMY_CAPTCHA: '$USE_DUMMY_CAPTCHA'"

if [[ "$USE_DUMMY_CAPTCHA" == "1" ]]
then
    docker_build_args+=( --build-arg USE_DUMMY_CAPTCHA="$USE_DUMMY_CAPTCHA" )
fi

USE_DUMMY_AUTH=${USE_DUMMY_AUTH:-}
echo "USE_DUMMY_AUTH: '$USE_DUMMY_AUTH'"

if [[ "$USE_DUMMY_AUTH" == "1" ]]
then
    docker_build_args+=( --build-arg USE_DUMMY_AUTH="$USE_DUMMY_AUTH" )
fi

docker_build_args+=(--tag "$image_name" .)

echo "The following image name will be used: $image_name"

tmp_outdir=$(mktemp -d)

set -x
DOCKER_BUILDKIT=1 docker build "${docker_build_args[@]}" --output "$tmp_outdir"
set +x

echo "Copying build output from $tmp_outdir to $PWD"
cp "$tmp_outdir/internet_identity.wasm" .

echo "Removing $tmp_outdir"
rm -rf "$tmp_outdir"
