#!/usr/bin/env bash
set -euo pipefail

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPTS_DIR/.."

curl_output=$(curl -sL "https://mds3.fidoalliance.org")
base64_content=$(echo "$curl_output" | awk -F'.' '{printf "%s", $2}' | tr '_-' '/+')
padding_needed=$((4 - ${#base64_content} % 4))
if [ $padding_needed -ne 4 ]; then
    base64_content="${base64_content}$(printf '=%.0s' $(seq 1 $padding_needed))"
fi
decoded_content=$(echo "$base64_content" | base64 --decode)

# FIDO entries (used as source for security keys)
declare -A fidoEntries
fidoEntries_json=$(echo "$decoded_content" | jq -r '.entries[] | select(.aaguid and ((.metadataStatement.attachmentHint // []) | type=="array" and index("external"))) | "\(.aaguid)=\(.metadataStatement.description)"')
while IFS="= " read -r key value; do
    fidoEntries["$key"]="$value"
done <<< "$fidoEntries_json"
{
    echo "{"
    for key in "${!fidoEntries[@]}"; do
        echo "  \"$key\": \"${fidoEntries[$key]}\","
    done | sed '$ s/,$//'
    echo "}"
} > "$PWD/src/frontend/src/lib/assets/aaguid/security_keys.json"

# Community entries (used as source for password managers)
declare -A communityEntries
while IFS="= " read -r key value; do
    communityEntries["$key"]="$value"
done < <(curl -sL "https://raw.githubusercontent.com/passkeydeveloper/passkey-authenticator-aaguids/main/aaguid.json" | jq -r 'to_entries | map("\(.key)=\(.value.name)") | .[]')
{
    echo "{"
    for key in "${!communityEntries[@]}"; do
        echo "  \"$key\": \"${communityEntries[$key]}\","
    done | sed '$ s/,$//'
    echo "}"
} > "$PWD/src/frontend/src/lib/assets/aaguid/password_managers.json"