#!/usr/bin/env bash
set -euo pipefail

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPTS_DIR/.."

JSON_FILE="$PWD/src/frontend/src/assets/passkey_aaguid_data.json"

TMP_FIDO=$(mktemp)
TMP_COMMUNITY=$(mktemp)
TMP_COMBINED=$(mktemp)
TMP_BASE64=$(mktemp)

if [[ -f "$JSON_FILE" ]]; then
    jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' "$JSON_FILE" > "$TMP_COMBINED"
else
    > "$TMP_COMBINED"
fi

curl -sL "https://mds3.fidoalliance.org" > "$TMP_FIDO"
cut -d'.' -f2 "$TMP_FIDO" > "$TMP_BASE64"

padding_needed=$((4 - $(wc -c < "$TMP_BASE64") % 4))
if [ $padding_needed -ne 4 ]; then
    printf '=%.0s' $(seq 1 $padding_needed) >> "$TMP_BASE64"
fi

base64 --decode --input="$TMP_BASE64" --output="$TMP_FIDO"

jq -r '.entries | map(select(.aaguid) | "\(.aaguid)=\(.metadataStatement.description)") | .[]' "$TMP_FIDO" > "$TMP_FIDO.tmp"
mv "$TMP_FIDO.tmp" "$TMP_FIDO"

curl -sL "https://raw.githubusercontent.com/passkeydeveloper/passkey-authenticator-aaguids/main/aaguid.json" | \
    jq -r 'to_entries | map("\(.key)=\(.value.name)") | .[]' > "$TMP_COMMUNITY"

declare -A combinedEntries

while IFS="= " read -r key value; do
    combinedEntries["$key"]="$value"
done < "$TMP_COMBINED"

while IFS="= " read -r key value; do
    combinedEntries["$key"]="$value"
done < "$TMP_FIDO"

while IFS="= " read -r key value; do
    combinedEntries["$key"]="$value"
done < "$TMP_COMMUNITY"

{
    echo "{"
    for key in "${!combinedEntries[@]}"; do
        echo "  \"$key\": \"${combinedEntries[$key]}\","
    done | sed '$ s/,$//'
    echo "}"
} > "$JSON_FILE"

rm -f "$TMP_FIDO" "$TMP_COMMUNITY" "$TMP_COMBINED" "$TMP_BASE64"

echo "Updated $JSON_FILE successfully."
