#!/usr/bin/env bash
set -euo pipefail

# A script that starts and stops selenium-standalone.
#
# Usage:
#
#   ./scripts/with-selenium-standalone <subcommand> ...
#
# After starting selenium-standalone, we wait for it to output a specific message
# ("Selenium started"), after which we know selenium itself was started. At this point
# we can start the subcommand.
#

selenium_standalone_args=("start" "--config" "./selenium-standalone.config.js")

echo "selenium-standalone" "${selenium_standalone_args[@]}"

sout=$(mktemp)
serr=$(mktemp)

if selenium-standalone "${selenium_standalone_args[@]}" \
    2> >(tee -a $serr) \
    > >(tee -a $sout) \
    &
then
    pid=$!
    echo "selenium-standalone started with pid $pid"

    attempts=0
    while ! grep -q 'Selenium started' "$sout"
    do
        attempts=$((attempts+1))
        if [ $attempts -le 10 ]
        then
            echo "selenium-standalone is not ready yet, retrying ($attempts)"
            sleep 2
        else
            echo "selenium-standalone didn't start successfully"

            echo "STDERR:" && touch "$serr" && cat "$serr" && rm "$serr"
            echo "STDOUT:" && touch "$sout" && cat "$sout" && rm "$sout"

            kill "$pid" || true
            exit 1
        fi
    done

    echo "selenium standalone is running"

    ret=0
    "$@" || ret="$?"

    touch "$serr" && cat "$serr" && rm "$serr"
    touch "$sout" && cat "$sout" && rm "$sout"

    echo "'$*' returned with $ret"

    kill "$pid" || echo "could not kill selenium-standalone"
    exit "$ret"
else
    echo "Could not start selenium-standalone server"
    echo "$sout"
    echo "$serr"
    exit 1
fi
