[package]
name = "canister_sig_util"
description = "Utils for handling canister signatures"
version = "0.1.0"
edition = "2021"

[dependencies]
# ic dependencies
candid = "0.9"
ic-cdk = "0.10"
ic-certified-map = "0.4"

# other dependencies
serde = { version = "1", features = ["rc"] }
serde_bytes = "0.11"
sha2 = "^0.10" # set bound to match ic-certified-map bound

[dev-dependencies]
rand = { version ="0.8.5" }
