name: 'uname'
description: This action reads the output of `uname` and forwards it as an output.
outputs:
  uname:
    description: "The output of 'uname -a'"
    value: ${{ steps.uname-run.outputs.uname }}
  uname-hash:
    description: "An hash of the output of 'uname -a'"
    value: ${{ steps.uname-run.outputs.uname-hash }}
runs:
  using: "composite"
  steps:
    - id: uname-run
      shell: bash
      run: |
        # print include system info relevant for cache compatibility
        uname="$(uname -mpsr)"
        echo "uname value:"
        echo "$uname"
        echo "::set-output name=uname::$uname"

        uname_hash="$(echo "$uname" | shasum -a 256 | head -c 10)"
        echo "uname hash value:"
        echo "$uname_hash"
        echo "::set-output name=uname-hash::$uname_hash"
