name: 'Check build'
description: This action performs a clean, non-Docker build of II, and optionally checks the gzipped Wasm module sha256 against the 'sha256' argument. Nothing is cached except for the bootstrap environment.
inputs:
  # This action should be self-contained, i.e. take no other inputs than the sha256, otherwise it is difficult to use it
  # in the release build check workflow. The reason is that this workflow runs off the latest main commit but checks out
  # this action as it was at the time of the most recent release. This means that any changes to the action's inputs will
  # not be reflected in the release build check workflow.
  sha256:
    description: The expected sha256 of the final production Wasm module
    required: false
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/bootstrap
    - uses: ./.github/actions/setup-node

    # run the build
    - run: npm ci
      shell: bash

    - name: Run build
      run: ./scripts/build
      shell: bash

    # check the hash
    - name: Check output hash
      shell: bash
      run: |
        sha256=$(shasum -a 256 ./internet_identity.wasm.gz | cut -d ' ' -f1)
        echo got sha "$sha256"
        if [ -n "${{ inputs.sha256 }}" ]
        then
          echo "checking build hash against ${{ inputs.sha256 }}"
          if [ "$sha256" == "${{ inputs.sha256 }}" ]
          then
            echo output sha256 matches expected
          else
            echo "sha mismatch: '$sha256' /= '${{ inputs.sha256 }}'"
            exit 1
          fi
        fi
