name: Backend tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  backend-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    env:
      GHC_VERSION: 8.8.4

    steps:
      - uses: actions/checkout@v2

      - name: Cache ~/.cabal/store
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
          key: cabal-${{ runner.os }}-${{ env.GHC_VERSION }}-${{ hashFiles('backend-tests/cabal.project', 'backend-tests//cabal.project.freeze') }}
          restore-keys: cabal-${{ runner.os }}-${{ env.GHC_VERSION }}-

      - name: Install Rust
        uses: ./.github/workflows/action.yml
        with:
          os: ${{ runner.os }}

      - uses: actions/setup-haskell@v1.1.3
        with:
          ghc-version: ${{ env.GHC_VERSION }}
          cabal-version: "3.2"

      - name: Build test runner
        run: |
          cd backend-tests
          cabal update
          # we cannot use `cabal install` because the build is performed in
          # another directory which breaks the relative path used in
          # backend-tests.hs to internet_identity.did
          cabal build --with-ghc ghc-${{ env.GHC_VERSION }}

      - name: Create fake assets
        run : |
          mkdir dist
          touch dist/index.html
          touch dist/index.js
          touch dist/index.js.gz
          touch dist/loader.webp
          touch dist/favicon.ico

      - name: Build backend canister
        run: |
          # we use the dummy_captcha feature which ensures the captcha string
          # is always "a"
          cargo build --features dummy_captcha --target wasm32-unknown-unknown --release

      - name: Run Tests
        shell: bash
        run: |
          cd backend-tests
          cabal run
