name: Backend tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  backend-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [ '1.51.0' ]
        ghc: ["8.8.4"]
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-1

      - name: Cache ~/.cabal/store
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
          key: cabal-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('backend-tests/cabal.project', 'backend-tests//cabal.project.freeze') }}
          restore-keys: cabal-${{ runner.os }}-${{ matrix.ghc }}-

      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
          rustup target add wasm32-unknown-unknown

      - uses: actions/setup-haskell@v1.1.3
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: "3.2"

      - name: Build test runner
        run: |
          cd backend-tests
          cabal update
          cabal install -w ghc-${{ matrix.ghc }} --overwrite-policy=always  --installdir=$HOME/bin

      - name: Create fake assets
        run : |
          mkdir dist
          touch dist/index.html
          touch dist/index.js
          touch dist/index.js.gz
          touch dist/loader.webp
          touch dist/favicon.ico

      - name: Build backend canister
        run: |
          cargo build --target wasm32-unknown-unknown --release

      - name: Run Tests
        shell: bash
        run: |
          cd backend-tests
          $HOME/bin/backend-tests --wasm ../target/wasm32-unknown-unknown/release/internet_identity.wasm\
