name: Cargo Fmt

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cargo-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    env:
      RUSTC_VERSION: 1.51.0

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-1

      - name: Install Rust
        run: |
          rustup update "$RUSTC_VERSION" --no-self-update
          rustup default "$RUSTC_VERSION"
          rustup target add wasm32-unknown-unknown
          rustup component add rustfmt

      - name: Cargo fmt
        shell: bash
        run: |
          cargo fmt
      - name: Commit Formatting changes
        uses: EndBug/add-and-commit@v7.2.0
        if: ${{ github.event_name == 'pull_request' }}
        with:
          add: src/internet_identity
          author_name: Formatting Committer
          author_email: "<nobody@example.com>"
          message: "Updating rust formatting"
          # do not pull: if this branch is behind, then we might as well let
          # the pushing fail
          pull_strategy: "NO-PULL"
