on:
  pull_request:
    types: [opened, reopened]

jobs:
  nudge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        env:
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        with:
          script: |
            const workflows = await github.paginate(github.rest.actions.listWorkflowRunsForRepo, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: process.env.PR_HEAD_REF,
                head_sha: process.env.PR_HEAD_SHA,
              });

            for (const workflow of workflows) {
              const jobs = await github.paginate(github.rest.actions.listJobsForWorkflowRun, {
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: workflow.run_id,
                }).filter(job => job.name.startsWith("report-"));

              for (const job of jobs) {
                console.log("Restarting reporting job", job);
                await github.paginate(github.rest.actions.reRunJobForWorkflowRun, {
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  job_id: job.id,
                });
              }
            }
