name: Install Rust
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
jobs:
  install-rust:
    runs-on: ${{ inputs.os }}
    env:
      RUSTC_VERSION: 1.51.0
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-1

      - name: Install Rust
        run: |
          rustup update "$RUSTC_VERSION" --no-self-update
          rustup default "$RUSTC_VERSION"
          rustup target add wasm32-unknown-unknown
          rustup component add rustfmt