# The jailbroken docker build.
name: Jailbroken Docker Build

on:
  push:

jobs:
  jailbreak-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Apply jailbreak patch
        working-directory: jailbreak
        run: |
          ./apply-patch
          echo "Patch was applied"
          git status

      # We use buildx and its GitHub Actions caching support `type=gha`. For
      # more information, see
      # https://github.com/docker/build-push-action/issues/539
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      # NOTE: could wait for main build
      - name: Build base Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          cache-from: type=gha,scope=cached-stage
          cache-to: type=gha,scope=cached-stage,mode=max
          outputs: type=cacheonly
          target: deps

      # TODO: add USE_DUMMY_CAPTCHA to docker build:
      - name: Build jailbroken internet identity
        uses: docker/build-push-action@v2
        with:
          build-args: II_ENV=development
          context: .
          file: Dockerfile
          cache-from: type=gha,scope=cached-stage
          # Exports the artefacts from the final stage
          outputs: .

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Run demo app
        run: |
          cd demos/sample-javascript/
          npm ci
          npm run build
          npm run develop --no-live-reload --no-devtool &
          sleep 10 # crude

      - name: Install DFX
        run: |
          echo Install DFX Version: "$DFX_VERSION"
          yes | sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"

      # Helps with debugging
      - name: Show versions
        run: |
          echo dfx --version
          dfx --version

      - name: Start replica
        run: |
          dfx start --background

      - name: Deploy II
        run: |
          echo installing
          shasum -a 256 ./internet_identity.wasm

          dfx canister --no-wallet create --all
          dfx canister --no-wallet install --mode reinstall internet_identity --argument '(null)'

      - name: Stop replica
        run: |
          dfx stop
