name: PR Review Requested

on:
  pull_request:
    types: [review_requested]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: ./.github/actions/slack
        with:
          WEBHOOK_URL: ${{ secrets.SLACK_PRIVATE_IDENTITY_WEBHOOK_URL }}
          MESSAGE: |
            New PR ready for review: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }}).

            Reviewer: <@${{ github.event.requested_reviewer.login == 'LXIF' && 'U07QU4DNV5Y' || github.event.requested_reviewer.login == 'sea-snake' && 'U07QU79GX0T' || github.event.requested_reviewer.login == 'lmuntaner' && 'U02TEQHKV35' || 'unknown' }}>
