on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const DIVIDER = "\n<!-- DIVIDER " + context.issue.number + "-->\n";
            const pr = await github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const [ descr, _outdated ] = pr.data.body.split(DIVIDER);
            const newSection = "Hello, world!";
            const newBody = [descr, newSection].join(DIVIDER);
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: newBody,
            });
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            console.log(artifacts);
