name: Say Hi

on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const DIVIDER = "\n<!-- DIVIDER " + context.issue.number + "-->\n";
            const pr = await github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const [ descr, _outdated ] = pr.data.body.split(DIVIDER);
            const newSection = "Hello, world!";
            const newBody = [descr, newSection].join(DIVIDER);
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: newBody,
            });






            const allArtifacts = await github.paginate(github.rest.actions.listArtifactsForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "showcase-build",
            });
            const artifactsByBranch = {};
            allArtifacts
              .filter(artifact => !artifact.expired)
              .filter(artifact => !artifact.workflow_run.head_branch.startsWith("gh-readonly-queue"))
              .forEach(artifact => {
                const branch = artifact.workflow_run.head_branch;
                artifactsByBranch[branch] = artifactsByBranch[branch] || [];
                artifactsByBranch[branch].push(artifact);
              });

            const artifacts = [];

            for(const branch in artifactsByBranch) {
              const branchArtifacts = [...artifactsByBranch[branch]];
              branchArtifacts.sort((a,b) => new Date(a.updated_at) - new Date(b.updated_at));
              const latestBranchArtifact = branchArtifacts[0];
              console.log("latest artifact in ", branch, latestBranchArtifact);
              artifacts.push(latestBranchArtifact);
            }

            artifacts.forEach( async (artifact) => {
              const name = artifact.name;
              const artifactId = artifact.id;
              const br = artifact.workflow_run.head_branch;
              console.log(artifact.name, artifactId);
              console.log(artifact.expires_at);
              console.log(br);
              const { url } = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifactId,
                archive_format: "zip",
              });
              console.log(url);
              await exec.exec('curl', ['-sSL', url, '-o', "out.zip"]);
              await io.mkdirP('out/' + br);
              await exec.exec('unzip', ["out.zip", '-d', 'out/' + br]);
            });
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'out'
