name: Selenium cross browser tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selenium-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [ '1.51.0' ]
        os: [ macos-latest ]
        dfx: [ '0.8.1' ]
        start-flag: [ '', '--emulator' ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-selenium-${{ hashFiles('**/Cargo.lock') }}-1

      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
          rustup target add wasm32-unknown-unknown

      # This step hangs on Github actions on Darwin for some reason, that
      # is why we run this only on Linux for now
      - name: Install DFX
        run: |
          export DFX_VERSION=${{ matrix.dfx }}
          echo Install DFX Version: $DFX_VERSION
          echo y | sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
          echo "$HOME/bin" >> $GITHUB_PATH

      - run: npm ci
      - run: dfx start ${{ matrix.start-flag }} --background

      - name: Deploy Internet Identity
        run: |
          export II_ENV=development
          dfx deploy --no-wallet --argument '(null)'

      - name: run mocked Internet Identity
        run: MOCK=true npm start &

      - name: Deploy whoami canister
        run: cd demos/whoami && dfx deploy --no-wallet

      - name: Run demo app
        run: |
          cd demos/sample-javascript/
          npm ci
          npm run build
          npm run develop --no-live-reload --no-devtool &
          sleep 10 # crude

      - name: install selenium webdrivers
        run: npm run install-webdrivers

      - run: npm run test:e2e-safari
      - run: dfx stop

      - name: Archive test logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: e2e-test-log ${{ matrix.start-flag }}
          path: wdio.log
