# A GitHub Actions workflow that regularly creates a pull request to update the IC dependencies
name: IC Dependencies Update

on:
  schedule:
    # create a new pull request every monday
    - cron:  '0 0 * * MON'

jobs:
  ic-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        # First, iterate over all Cargo.toml files and check against IC GitHub for new commits.
      - name: Check new ic version
        id: update
        run: |
          shopt -s globstar
          
          need_update=false
          latest_ic_commit=$(curl --silent -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/dfinity/ic/commits/master | jq -cMr .sha)

          echo "latest ic commit '$latest_ic_commit'"
          for filename in **/Cargo.toml; do
            echo Checking "$filename"
            [ -e "$filename" ] || continue
            if ! grep -q https://github\.com/dfinity/ic "$filename"; then
              echo "$filename" does not contain ic dependecy, skipping
              continue
            fi
          
            current_ic_commit=$(cat "$filename" | sed -n 's/.*{\s*git\s*=\s*"https:\/\/github\.com\/dfinity\/ic",\s*rev\s*=\s*"\([a-z0-9]*\)" }.*/\1/p' | head -n 1)
            echo "current ic commit '$current_ic_commit'"
          
            if [ "$current_ic_commit" != "$latest_ic_commit" ]; then
              sed -i -e "s/$current_ic_commit/$latest_ic_commit/g" "$filename"
              need_update=true
            fi
          done
          
          if $need_update; then
            echo IC dependencies need an update
            echo "updated=1" >> "$GITHUB_OUTPUT"
          else
            echo "updated=0" >> "$GITHUB_OUTPUT"
          fi

      - uses: ./.github/actions/bootstrap

        # Make sure Cargo.lock is up-to-date
      - name: Update lockfile
        run: cargo generate-lockfile

        # If the ic commit was updated, create a PR.
      - name: Create Pull Request
        if: ${{ steps.update.outputs.updated == '1' }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GIX_BOT_PAT }}
          base: main
          add-paths: |
            ./**/Cargo.toml
            Cargo.lock
          commit-message: Update commit of IC dependencies
          committer: GitHub <noreply@github.com>
          author: gix-bot <gix-bot@users.noreply.github.com>
          branch: bot-ic-update
          delete-branch: true
          title: 'Update commit of IC dependencies '

        # Since the this is a scheduled job, a failure won't be shown on any
        # PR status. To notify the team, we send a message to our Slack channel on failure.
      - name: Notify Slack on failure
        uses: ./.github/actions/slack
        if: ${{ failure() }}
        with:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MESSAGE: "IC commit update failed"
