name: TODO

on:
  push:
    # TODO: pull_request & workflow_run

jobs:
  vdiffs:
    concurrency:
      group: vdiffs-${{ github.ref_name || github.run_id }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
      - name: "Find PR"
        id: "pr"
        uses: actions/github-script@v5
        with:
          script: |
            const refName = "nm-say-hi"; // process.env.GITHUB_REF_NAME;
            if(!refName) {
              const msg = "No ref for run, aborting";
              console.error(msg);
              throw new Error(msg);
            }
            console.log("Looking for PR for", refName);
            const res = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "dfinity:" + refName,
            })
            console.log(res);
            const pulls = res.data;
            if(pulls.length === 0) {
              return null;
            } else if (pulls.length !== 1) {
              const msg = "Expecting one PR, got " + pulls.length;
              console.error(msg);
              throw new Error(msg);
            }

            const pull = pulls[0];
            return { pr: pull.number, head: pull.head.ref, base: pull.base.ref }

      - uses: actions/checkout@v3
      - name: "Output"
        if: ${{fromJSON(steps.pr.outputs.result) != null}}
        run: |
          echo "${{ github.pr.outputs.result }}"
          echo "${{ github.pr.outputs.result }}" | jq
          echo "PR is ${{ github.pr.outputs.result.pr }}"
          echo "head is ${{ github.pr.outputs.result.head }}"
          echo "base is ${{ github.pr.outputs.result.base }}"
          git checkout --orphan "vdiffs/${{ github.pr.outputs.result.head }}"
          git reset --hard
          git fetch orign "screenshots/${{ github.pr.outputs.result.head }}":"screenshots/${{ github.pr.outputs.result.head }}"
          git fetch orign "screenshots/${{ github.pr.outputs.result.base }}":"screenshots/${{ github.pr.outputs.result.base }}"
