name: TODO

on:
  push:
    # TODO: pull_request & workflow_run

jobs:
  vdiffs:
    concurrency:
      group: vdiffs-${{ github.ref_name || github.run_id }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
      - name: "Find PR"
        id: "pr"
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: |
            const refName = "nm-say-hi"; // process.env.GITHUB_REF_NAME;
            if(!refName) {
              const msg = "No ref for run, aborting";
              console.error(msg);
              throw new Error(msg);
            }
            console.log("Looking for PR for", refName);
            const res = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "dfinity:" + refName,
            })
            console.log(res);
            const pulls = res.data;
            if(pulls.length !== 1) {
              const msg = "Expecting one PR, got " + pulls.length;
              console.error(msg);
              throw new Error(msg);
            }

            return pulls[0].number;

      - name: "Output"
        run: |
          echo "branch is ${{github.ref_name}} with PR ${{steps.pr.outputs.result}}"
