name: TODO

on:
  push:
    # TODO: pull_request & workflow_run

jobs:
  vdiffs:
    concurrency:
      group: vdiffs-${{ github.ref_name || github.run_id }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
      - name: "Find PR"
        id: "pr"
        uses: actions/github-script@v5
        with:
          script: |
            const refName = process.env.GITHUB_REF_NAME;
            if(!refName) {
              const msg = "No ref for run, aborting";
              console.error(msg);
              throw new Error(msg);
            }
            console.log("Looking for PR for", refName);
            const res = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "dfinity:" + refName,
            })
            console.log(res);
            const pulls = res.data;
            if(pulls.length === 0) {
              return null;
            } else if (pulls.length !== 1) {
              const msg = "Expecting one PR, got " + pulls.length;
              console.error(msg);
              throw new Error(msg);
            }

            const pull = pulls[0];
            return { pr: pull.number, head: pull.head.ref, base: pull.base.ref }

      - uses: actions/checkout@v3
      - name: "Output"
        if: ${{fromJSON(steps.pr.outputs.result) != null}}
        env:
          pr: ${{fromJSON(steps.pr.outputs.result).pr}}
          base: ${{fromJSON(steps.pr.outputs.result).base}}
          head: ${{fromJSON(steps.pr.outputs.result).head}}
        run: |
          echo "PR is ${{ env.pr }}"
          echo "head is ${{ env.head }}"
          echo "base is ${{ env.base }}"

          git fetch origin "screenshots/${{ env.head }}":"screenshots/${{ env.head }}"
          git fetch origin "screenshots/${{ env.base }}":"screenshots/${{ env.base }}"

          # actual checkout
          git checkout --orphan "vdiffs/${{ env.head }}"
          git reset --hard

          for modified in $(git diff --name-only "screenshots/${{ env.base }}" "screenshots/${{ env.head }}" -- '*.png')
          do
            echo "updated screenshot: $modified"
            base_screenshot=$(mktemp)
            head_screenshot=$(mktemp)

            git show "screenshots/${{ env.base }}":"$modified" > "$base_screenshot"
            git show "screenshots/${{ env.head }}":"$modified" > "$head_screenshot"

            mkdir -p $(dirname "$modified")
            compare -verbose "$base_screenshot" "$head_screenshot" "$modified"

            rm "$base_screenshot"
            rm "$head_screenshot"
          done

          git add screenshots
          git config user.name "vdiffer"
          git config user.email "<>"
          git commit -am "Vdiffs for ${{ env.base }} -> ${{ env.head }}"
          git config --add --bool push.autoSetupRemote true
          git push --force
