name: 'Setup DFX'
description: Setup DFX
inputs:
  dfx-version:
    default: 0.14.0
    description: The dfx version to be installed or loaded from cache.
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: |
          /usr/local/bin/dfx
        key: dfx-cache-${{ inputs.dfx-version }}-5
    - name: Install DFX
      shell: bash
      run: |
        if command -v dfx
        then
          echo "DFX restored from cache"
        else
          echo "DFX not restored from cache, running install script:"
          DFX_VERSION=${{ inputs.dfx-version }} sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
        fi
        echo "DFX version"
        dfx --version

    - name: Configure network
      shell: bash
      run: |
        mkdir -p "$HOME/.config/dfx"
        echo '{"local": {"bind": "0.0.0.0:4943","type": "ephemeral"}}' > "$HOME/.config/dfx/networks.json"
