name: 'Setup DFX'
description: Setup DFX
runs:
  using: "composite"
  steps:
    - name: Set DFX version
      shell: bash
      run: |
        echo "DFX_VERSION=0.11.1" >> $GITHUB_ENV
    - uses: actions/cache@v2
      with:
        path: |
          /usr/local/bin/dfx
          ~/.cache/dfinity
        key: dfx-cache-${{ env.DFX_VERSION }}-3
    - name: Install DFX
      shell: bash
      run: |
        if [[ "$(command -v dfx)" ]]
        then
          echo "DFX restored from cache"
        else
          echo "DFX not restored from cache, running install script:"
          (yes || true) | sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
        fi
        echo "DFX version"
        dfx --version
