name: 'Setup DFX'
description: Setup DFX
inputs:
  dfx-version:
    default: 0.14.0
    description: The dfx version to be installed or loaded from cache.
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: |
          /usr/local/bin/dfx
        key: dfx-cache-${{ inputs.dfx-version }}-5
    - name: Install dfx
      uses: dfinity/setup-dfx@main
      with:
        dfx-version: ${{ inputs.dfx-version }}
    - name: Configure network
      shell: bash
      run: |
        mkdir -p "$HOME/.config/dfx"
        echo '{"local": {"bind": "0.0.0.0:4943","type": "ephemeral"}}' > "$HOME/.config/dfx/networks.json"
