[workspace]

[package]
name = "vc_issuer"
description = "Verifiable Credentials Issuer"
version = "0.1.0"
edition = "2021"

[dependencies]
# local dependencies
internet_identity_interface = { path = "../../src/internet_identity_interface" }
# ic dependencies
candid = "0.8"
ic-cdk = "0.9"
ic-cdk-macros = "0.6"
# vc dependencies
# ssi-dids = { version = "0.1", features = ["example"] }
# ssi-vc = "0.2"
identity_credential = {git = "https://github.com/frederikrothenberger/identity.rs.git", branch = "frederik/wasm-test", default-features = false, features = ["credential"]}
identity_core = {git = "https://github.com/frederikrothenberger/identity.rs.git", branch = "frederik/wasm-test", default-features = false}
# other dependencies
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
ic-test-state-machine-client = "2"
canister_tests = { path = "../../src/canister_tests" }
lazy_static = "1.4"
